[package]
name = "flat_knn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
memmap2 = "0.9.4"
ordered-float = "4.2.0"
simsimd = "3.9.0"
